### PR TITLE
Add symfony task to enable doctrine database creation on provisioning

### PR DESCRIPTION
**Pull request by dennisdegreef**
When `symfony: "yes"` is being set, the symfony task is being included, and provisioning should create a doctrine database.

### CODE REVIEW

**Comment by ShawnMcCool** [comment]
I'm wondering if this should be more specific than "symfony yes". Any thoughts on that?

**Comment by dennisdegreef** [comment]
Yes, I was thinking about that when making it as well, would `is_symfony` be a better name? to indicate a symfony application?

**Comment by ShawnMcCool** [comment]
What about an option to "run shell script on provision" where you enter the path to a shell script.

**Comment by fvdb** [comment]
Just because I run Symfony doesn't mean I use Doctrine, or even make use of schema:create (migrations, other datastores, etc), so in that sense "symfony yes" is a misnomer. It also suggests that Symfony would be added to the machine, which isn't the case.

I also think that something like "symfony database schema create yes" is too specific a use case to be included. Also, if you are looking to run a shell script on provision, why not simply add config.vm.provision "shell" to the vagrant file?

**Comment by ShawnMcCool** [comment]
Yes, I forgot that actually. Very good point on the shell script. Thanks @fvdb, head has been out of this game for a while.

**Comment by ShawnMcCool** [comment]
@dennisdegreef thanks for the PR. But, I think that you can do this well with a shell-script provisioner.

**Comment by dennisdegreef** [comment]
No problem, also sounds like the better solution which I didn't think of :)

**Pull request closed without merging**
